#!/usr/bin/env bash
set -euo pipefail
ROOT="/data/sony/LFCRASH/LFCRASH-CBM"
CONCEPT_FILE="$ROOT/output/concept_sets/perfect_concept_set_v1.txt"

nohup python3 "$ROOT/train_dad_ac.py" --gpu 0 --tag dad_ac_perfect_v1_h384_tinyalign_local_q1 --epochs 60 --warmup_epochs 12 --cbm_ramp_epochs 18 --batch_size 16 --lr 3e-4 --h_dim 384 --z_dim 384 --lambda_align 1e-6 --lambda_sparse 5e-5 --lambda_recon 1e-4 --lambda_ac_policy 0.3 --lambda_ac_value 0.3 --ac_gamma 0.95 --ac_entropy 0.01 --num_concepts 80 --concept_file "$CONCEPT_FILE" --eval_every 5 --num_workers 4 > "$ROOT/output/dad_ac/dad_ac_perfect_v1_h384_tinyalign_local_q1/nohup.log" 2>&1 &
nohup python3 "$ROOT/train_dad_ac.py" --gpu 2 --tag dad_ac_perfect_v1_h384_lowac_weaksparse_local_q2 --epochs 60 --warmup_epochs 12 --cbm_ramp_epochs 18 --batch_size 16 --lr 3e-4 --h_dim 384 --z_dim 384 --lambda_align 0 --lambda_sparse 1e-5 --lambda_recon 1e-4 --lambda_ac_policy 0.1 --lambda_ac_value 0.1 --ac_gamma 0.95 --ac_entropy 0.01 --num_concepts 80 --concept_file "$CONCEPT_FILE" --eval_every 5 --num_workers 4 > "$ROOT/output/dad_ac/dad_ac_perfect_v1_h384_lowac_weaksparse_local_q2/nohup.log" 2>&1 &
nohup python3 "$ROOT/train_multi.py" --dataset dad --gpu 3 --tag dad_multi_perfect_v1_h384_lowac_local_q3 --epochs 50 --warmup_epochs 10 --cbm_ramp_epochs 15 --batch_size 16 --lr 3e-4 --h_dim 384 --lambda_align 1e-6 --lambda_sparse 5e-5 --lambda_recon 1e-4 --lambda_ac_policy 0.1 --lambda_ac_value 0.1 --num_concepts 80 --concept_file "$CONCEPT_FILE" --eval_every 5 --num_workers 4 > "$ROOT/output/dad_ac/dad_multi_perfect_v1_h384_lowac_local_q3/nohup.log" 2>&1 &
nohup python3 "$ROOT/train_multi.py" --dataset a3d --gpu 1 --tag a3d_ac_perfect_v1_minuscgta_lowac_nosparse_local_q1 --epochs 50 --warmup_epochs 10 --cbm_ramp_epochs 15 --batch_size 16 --lr 3e-4 --h_dim 256 --disable_cgta --lambda_align 0 --lambda_sparse 0 --lambda_recon 1e-4 --lambda_ac_policy 0.05 --lambda_ac_value 0.1 --num_concepts 80 --concept_file "$CONCEPT_FILE" --eval_every 5 --num_workers 4 > "$ROOT/output/a3d_ac/a3d_ac_perfect_v1_minuscgta_lowac_nosparse_local_q1/nohup.log" 2>&1 &
nohup python3 "$ROOT/train_multi.py" --dataset a3d --gpu 5 --tag a3d_ac_perfect_v1_minuscgta_lowac_norecon_local_q2 --epochs 50 --warmup_epochs 10 --cbm_ramp_epochs 15 --batch_size 16 --lr 3e-4 --h_dim 256 --disable_cgta --lambda_align 0 --lambda_sparse 5e-5 --lambda_recon 0 --lambda_ac_policy 0.05 --lambda_ac_value 0.1 --num_concepts 80 --concept_file "$CONCEPT_FILE" --eval_every 5 --num_workers 4 > "$ROOT/output/a3d_ac/a3d_ac_perfect_v1_minuscgta_lowac_norecon_local_q2/nohup.log" 2>&1 &
nohup python3 "$ROOT/train_multi.py" --dataset a3d --gpu 6 --tag a3d_ac_perfect_v1_minuscgta_tinyalign_local_q3 --epochs 50 --warmup_epochs 10 --cbm_ramp_epochs 15 --batch_size 16 --lr 3e-4 --h_dim 256 --disable_cgta --lambda_align 1e-6 --lambda_sparse 5e-5 --lambda_recon 1e-4 --lambda_ac_policy 0.3 --lambda_ac_value 0.3 --num_concepts 80 --concept_file "$CONCEPT_FILE" --eval_every 5 --num_workers 4 > "$ROOT/output/a3d_ac/a3d_ac_perfect_v1_minuscgta_tinyalign_local_q3/nohup.log" 2>&1 &
wait
