#!/usr/bin/env python3
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
OUT_DIR = ROOT / "output" / "emnlp2026_support"


def load_json(path: Path):
    return json.loads(path.read_text())


def pct(value: float) -> str:
    return f"{100.0 * value:.2f}\\%"


def sec(value: float) -> str:
    return f"{value:.2f}s"


def pm_pct(mean_value: float, std_value: float) -> str:
    return f"{100.0 * mean_value:.2f}\\% $\\pm$ {100.0 * std_value:.2f}"


def pm_sec(mean_value: float, std_value: float) -> str:
    return f"{mean_value:.2f}s $\\pm$ {std_value:.2f}s"


def concept_label(name: str) -> str:
    return {
        "historical_full": "Historical full",
        "risk_core_v1": "Risk-core manual",
        "perfect_v1": "Perfect concept set v1",
    }[name]


def dataset_label(name: str) -> str:
    return {"dad": "DAD", "a3d": "A3D"}[name]


def build_single_seed_table(controlled):
    lines = []
    for run in controlled["runs"]:
        if not run["completed"]:
            continue
        lines.append(
            f"{dataset_label(run['dataset'])} & {concept_label(run['concept_set'])} & "
            f"{run['concept_count']} & {pct(run['AP'])} & {sec(run['mTTA'])} & "
            f"{sec(run['TTA_R80'])} & {run['P_R80']:.3f} \\\\"
        )
    return "\n".join(lines)


def build_multiseed_table(multiseed):
    lines = []
    for row in multiseed["rows"]:
        aggregate = row.get("aggregate")
        if aggregate is None:
            ap = "--"
            mtta = "--"
            tta_r80 = "--"
            p_r80 = "--"
        else:
            ap = pm_pct(aggregate["AP"]["mean"], aggregate["AP"]["std"])
            mtta = pm_sec(aggregate["mTTA"]["mean"], aggregate["mTTA"]["std"])
            tta_r80 = pm_sec(aggregate["TTA_R80"]["mean"], aggregate["TTA_R80"]["std"])
            p_r80 = f"{aggregate['P_R80']['mean']:.3f} $\\pm$ {aggregate['P_R80']['std']:.3f}"

        status_bits = [f"{row['num_completed']}/{row['num_expected']} seeds"]
        if row.get("num_in_progress"):
            status_bits.append(f"{row['num_in_progress']} running")
        if row.get("num_queued"):
            status_bits.append(f"{row['num_queued']} queued")
        lines.append(
            f"{dataset_label(row['dataset'])} & {concept_label(row['concept_set'])} & "
            f"{row['concept_count']} & {ap} & {mtta} & {tta_r80} & {p_r80} & "
            f"{'; '.join(status_bits)} \\\\"
        )
    return "\n".join(lines)


def build_status_lines(multiseed, a3d_headline):
    completed_cells = sum(row["num_completed"] for row in multiseed["rows"])
    expected_cells = sum(row["num_expected"] for row in multiseed["rows"])
    running_cells = sum(row.get("num_in_progress", 0) for row in multiseed["rows"])
    queued_cells = sum(row.get("num_queued", 0) for row in multiseed["rows"])

    ontology_line = (
        f"Controlled ontology multi-seed status: {completed_cells}/{expected_cells} seeded cells completed"
    )
    suffix = []
    if running_cells:
        suffix.append(f"{running_cells} running")
    if queued_cells:
        suffix.append(f"{queued_cells} queued")
    if suffix:
        ontology_line += f" ({'; '.join(suffix)})"
    ontology_line += "."

    headline_line = (
        f"A3D headline multi-seed status: {a3d_headline['num_completed']}/{a3d_headline['num_expected']} completed"
    )
    if a3d_headline.get("num_in_progress"):
        headline_line += f", {a3d_headline['num_in_progress']} running"
    headline_line += "."

    if "aggregate_best_so_far" in a3d_headline:
        agg = a3d_headline["aggregate_best_so_far"]
        headline_line += (
            f" Current best-so-far aggregate: AP={pm_pct(agg['AP']['mean'], agg['AP']['std'])}, "
            f"mTTA={pm_sec(agg['mTTA']['mean'], agg['mTTA']['std'])}."
        )

    return ontology_line, headline_line


def main():
    controlled = load_json(OUT_DIR / "controlled_ontology_status.json")
    multiseed = load_json(OUT_DIR / "multiseed_ontology_status.json")
    a3d_headline = load_json(OUT_DIR / "a3d_headline_multiseed_status.json")

    single_seed_rows = build_single_seed_table(controlled)
    multiseed_rows = build_multiseed_table(multiseed)
    ontology_line, headline_line = build_status_lines(multiseed, a3d_headline)

    tex_lines = [
        "% Auto-generated by export_emnlp_status_snippets.py",
        "% Single-seed controlled ontology rows for Table~\\ref{tab:concept_sets}",
        single_seed_rows,
        "",
        "% Multi-seed controlled ontology summary rows for an appendix/support table",
        multiseed_rows,
        "",
        "% Status lines for paper notes / rebuttal / tracker",
        f"% {ontology_line}",
        f"% {headline_line}",
        "",
    ]

    md_lines = [
        "# EMNLP Status Snippets",
        "",
        "## Controlled Ontology Single-Seed Rows",
        "",
        "```tex",
        single_seed_rows,
        "```",
        "",
        "## Controlled Ontology Multi-Seed Rows",
        "",
        "```tex",
        multiseed_rows,
        "```",
        "",
        "## Status Notes",
        "",
        f"- {ontology_line}",
        f"- {headline_line}",
        "",
    ]

    tex_path = OUT_DIR / "emnlp_status_snippets.tex"
    md_path = OUT_DIR / "emnlp_status_snippets.md"
    tex_path.write_text("\n".join(tex_lines))
    md_path.write_text("\n".join(md_lines))
    print(f"[wrote] {tex_path}")
    print(f"[wrote] {md_path}")


if __name__ == "__main__":
    main()
